# Generated by Django 2.2.5 on 2019-09-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_adress',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
