# Generated by Django 2.2.5 on 2019-09-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_shipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
