# Generated by Django 2.2.5 on 2019-09-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190926_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reputation',
            field=models.FloatField(default=0),
        ),
    ]
