# Generated by Django 2.2.5 on 2019-09-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190926_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.CharField(error_messages={'unique': 'A user with that id already exists'}, max_length=255, unique=True, verbose_name='Identification document'),
        ),
    ]
