# Generated by Django 2.2.5 on 2019-09-27 23:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190926_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipper',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='shipper',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='created',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reputation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='designer',
            name='order_address',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='shipper',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
