# Generated by Django 2.2.5 on 2019-09-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190929_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='billing_adress',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
