# Generated by Django 2.2.5 on 2019-09-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190929_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
