# Generated by Django 2.2.5 on 2019-09-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190929_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='billing_adress',
            new_name='billing_address',
        ),
    ]
