# Generated by Django 2.2.5 on 2019-09-29 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190929_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +9999999999. Up to 20 digits allowed.', regex='^(\\(?\\+?[0-9]*\\)?)?[0-9_\\- \\(\\)]*$')]),
        ),
    ]
