version: '2'

services:
  db:
    extends:
      file: base.yml
      service: db

  main:
    extends:
      file: base.yml
      service: main
    build:
      args:
        - DJANGO_ENV=dev
    command: start
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    volumes:
      - ./tShoes-main:/main_app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db_data:
    external: true