version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ./compose/local/django/start.sh
  db:
    image: postgres
    env_file:
      - ./.envs/.postgres
