# Generated by Django 2.2.5 on 2019-09-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='reference',
            new_name='reference_name',
        ),
        migrations.AddField(
            model_name='reference',
            name='max_stock',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='reference',
            name='min_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
