# Generated by Django 2.2.5 on 2019-09-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20190914_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='reference',
            name='price',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='reference',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/references/', verbose_name='Image of the reference to buy'),
        ),
    ]
