# Generated by Django 2.2.5 on 2019-09-28 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_auto_20190926_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='inventory.Inventory'),
        ),
    ]
