# Generated by Django 2.2.5 on 2019-09-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_auto_20190928_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
