# Generated by Django 2.2.5 on 2019-09-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_auto_20190928_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
