# Generated by Django 2.2.5 on 2019-10-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('order', '0001_initial'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='references',
            field=models.ManyToManyField(through='reference.Item', to='reference.Reference'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipper_order', to='users.Shipper'),
        ),
    ]
