# Generated by Django 2.2.5 on 2019-09-13 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='designer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Designer', to='users.Designer'),
        ),
    ]
