# Generated by Django 2.2.5 on 2019-09-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='references',
            field=models.ManyToManyField(through='reference.Item', to='reference.Reference'),
        ),
    ]
