# Generated by Django 2.2.5 on 2019-09-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190927_2327'),
        ('reference', '0003_auto_20190926_2249'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Designer'),
        ),
        migrations.AddField(
            model_name='order',
            name='optional_adress',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='references',
            field=models.ManyToManyField(through='reference.Item', to='reference.Reference'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Shipper'),
        ),
    ]
