# Generated by Django 2.2.5 on 2019-09-28 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190927_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_order', to='users.Designer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipper_order', to='users.Shipper'),
        ),
    ]
