# Generated by Django 2.2.5 on 2019-10-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191001_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='optional_adress',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
