# Generated by Django 2.2.5 on 2019-09-14 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_shipper'),
        ('order', '0003_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Shipper'),
        ),
    ]
