# Generated by Django 2.2.5 on 2019-10-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20191001_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='optional_adress',
            new_name='optional_address',
        ),
    ]
