# Generated by Django 2.2.5 on 2019-09-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190928_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='designer',
        ),
    ]
