# Generated by Django 2.2.5 on 2019-09-26 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190926_2249'),
        ('order', '0004_order_shipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Designer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Customer'),
        ),
    ]
