# Generated by Django 2.2.5 on 2019-10-01 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191001_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.SET_DEFAULT, to='order.Status'),
        ),
    ]
