# Generated by Django 2.2.5 on 2019-10-01 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191001_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='value',
            field=models.CharField(choices=[(0, 'none'), (1, 'placed'), (2, 'shipped'), (3, 'on_the_way'), (4, 'arrived'), (5, 'missing')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='order.Status'),
        ),
    ]
