# Generated by Django 2.2.5 on 2019-10-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, 'placed'), (2, 'shipped'), (3, 'on_the_way'), (4, 'arrived'), (5, 'missing')], default=0),
        ),
    ]
